#!/bin/bash

function init {                                                           # dirs used by:
  mkdir -p ./data/raw      ./data/state                                   # download.sh
  mkdir -p ./data/windows  ./data/targets                                 # 
  mkdir -p ./data/analysis ./data/forecast                                # analyze.sh
  mkdir -p ./data/output   ./data/stream

  date +"%Y.%j.%H.%M.%S"
  echo -n "age: "
  age_file=./data/state/age
  if [[ ! -f "${age_file}" ]]; then
    echo -n 0 > ${age_file}  
    echo -n 0;
  else
    tmp=`cat ${age_file}` 
    let tmp=tmp+1
    echo -n ${tmp} > ${age_file}
    echo -n ${tmp}
  fi
}

function download {
  cd 0_download
  ./download.sh 
  cd ..      
}

function analyze {
  cd 1_analyze
  ./analyze.sh 
  cd ..       
}


while true
do
  
  init
  echo
  download
  SECONDS=0   
  echo 
  analyze                                 
  echo
 
  echo -n " | runtime: ${SECONDS}sec"

  let LEFT=60-SECONDS
  if [[ $LEFT -gt 0 ]]
  then
    sleep $LEFT
  fi
  echo " *"
done

