#!/bin/bash

function init {                                                           # dirs used by:
  mkdir -p ./data/raw      ./data/state     ./data/vectors                # download.sh
  mkdir -p ./data/windows  ./data/targets                                 # 
  mkdir -p ./data/analysis ./data/forecast                                # analyze.sh
#  mkdir -p ./data/training ./data/modeling
#  mkdir -p ./data/labels   ./data/predictions
#  mkdir -p ./data/utility

  date +"%Y.%j.%H.%M.%S"
  echo -n "age: "
  age_file=./data/state/age
  if [[ ! -f "${age_file}" ]]; then
    echo -n 0 > ${age_file}  
    echo -n 0;
  else
    tmp=`cat ${age_file}` 
    let tmp=tmp+1
    echo -n ${tmp} > ${age_file}
    echo -n ${tmp}
  fi
  echo
}

function download {
  cd 0_download
  ./download.sh 
  cd ..
}

function download_all {
  cd 0_download
  ./download_all.sh 
  cd ..
}

function sync {
  ./scripts/extract_raws.sh
}

function output {
  cd 3_output
  ./make_output.sh
  cd ..
}

function client {
  echo 
  SECONDS=0    
  init
  echo " | client"
  download
  ./scripts/upload_to_server.sh
  echo " | runtime: ${SECONDS}sec"
}

function server {
  while true
  do
    echo 
    SECONDS=0   
    init
    download_all
    sync
    output
    echo -n " | runtime: ${SECONDS}sec"
    let LEFT=60-SECONDS
    if [[ $LEFT -gt 0 ]]
    then
      sleep $LEFT
    fi
    echo " *"
  done
}

client
#server
