cmake -D DEBUG=OFF \
      -D PROFILE=OFF \
      -D ARMA_EXTRA_DEBUG=OFF \
      -D BUILD_CLI_EXECUTABLES=ON \
      -D BUILD_PYTHON_BINDINGS=OFF \
      -D BUILD_JULIA_BINDINGS=OFF \
      -D BUILD_GO_BINDINGS=OFF \
      -D BUILD_GO_SHLIB=OFF \
      -D BUILD_R_BINDINGS=OFF \
      -D BUILD_TESTS=ON \
      -D BUILD_SHARED_LIBS=OFF \
      -D DISABLE_DOWNLOADS=OFF \
      -D DOWNLOAD_ENSMALLEN=ON \
      -D DOWNLOAD_STB_IMAGE=ON \
      -D USE_OPENMP=ON \
      -D CMAKE_BUILD_TYPE=Release \
      -D CMAKE_CXX_FLAGS_RELEASE="-O3" \
      ../
